name: Fibonacci C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile and Run Unit Tests
        run: |
          g++ -o fibonacci_test fibonacci_test.cpp
          ./fibonacci_test

