name: Todo app build

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the `main` branch
      
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the code from the repository

      - name: Set up C environment
        run: sudo apt-get update && sudo apt-get install -y build-essential  # Install build tools like GCC

      - name: Compile C code
        run: g++ -o fibonacci fibonacci.c  # Compile the `fibonacci.c` program to an executable named `fibonacci`

      - name: Run the C program
        run: ./todo  # Run the compiled program
